### ISSUE TITLE
gx publish breaks on symbolic links (panic: runtime error: slice bounds out of range)

### ISSUE THREAD

**Issue by hermanjunge** [whyrusleeping/gx#132]
How to replicate

```bash
[ hj: go-cid ]$ pwd ## Original path
/Users/hj/dev/go/src/github.com/ipfs/go-cid
[ hj: go-cid ]$ gx publish
package go-cid published with hash: QmWi4ZH2kirAYaCji2sjVjqrovx1Vwv8YXWspmxH6VBS7N
[ hj: go-cid ]$ ln -s /Users/hj/dev/go/src/github.com/ipfs/go-cid /tmp/go-cid # Symbolic link
[ hj: go-cid ]$ cd /tmp/go-cid
[ hj: go-cid ]$ git checkout -- .gx/lastpubver ## Undo the publish, for replication purposes
[ hj: go-cid ]$ gx publish
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x3b76e0, 0xc420010120)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/whyrusleeping/gx/gxutil.(*PM).PublishPackage.func1(0xc420010034, 0xb, 0x6f2f00, 0xc4200761a0, 0x0, 0x0, 0x0, 0x0)
	/Users/hj/dev/go/src/github.com/whyrusleeping/gx/gxutil/publish.go:61 +0x579
path/filepath.walk(0xc420010034, 0xb, 0x6f2f00, 0xc4200761a0, 0xc420456240, 0x0, 0xc420070001)
	/usr/local/go/src/path/filepath/path.go:351 +0x81
path/filepath.Walk(0xc420010034, 0xb, 0xc420456240, 0x6ec9a0, 0xc420075950)
	/usr/local/go/src/path/filepath/path.go:398 +0xd5
github.com/whyrusleeping/gx/gxutil.(*PM).PublishPackage(0xc420016270, 0xc420010034, 0xb, 0xc420424000, 0x4e00, 0x0, 0x0, 0x0)
	/Users/hj/dev/go/src/github.com/whyrusleeping/gx/gxutil/publish.go:99 +0x5bd
main.doPublish(0xc420424000, 0x6, 0xc420010cc6)
	/Users/hj/dev/go/src/github.com/whyrusleeping/gx/main.go:184 +0xf3
main.glob..func1(0xc42040c420, 0x0, 0xc42040c420)
	/Users/hj/dev/go/src/github.com/whyrusleeping/gx/main.go:170 +0x21e
github.com/codegangsta/cli.HandleAction(0x3a40a0, 0x573c68, 0xc42040c420, 0xc420422000, 0x0)
	/Users/hj/dev/go/src/github.com/codegangsta/cli/app.go:490 +0xd4
github.com/codegangsta/cli.Command.Run(0x41d2a7, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x420f1d, 0x11, 0x0, ...)
	/Users/hj/dev/go/src/github.com/codegangsta/cli/command.go:210 +0xbb9
github.com/codegangsta/cli.(*App).Run(0xc4200016c0, 0xc420080060, 0x2, 0x2, 0x0, 0x0)
	/Users/hj/dev/go/src/github.com/codegangsta/cli/app.go:255 +0x7b2
main.main()
	/Users/hj/dev/go/src/github.com/whyrusleeping/gx/main.go:118 +0x652
[ hj: go-cid ]$ cd /Users/hj/dev/go/src/github.com/ipfs/go-cid ## Let's try it at the original path
[ hj: go-cid ]$ gx publish
package go-cid published with hash: QmcGM7xckxyobJNdZbDP68PxC9QJBdRAXNYbEG9YhjMM6z
[ hj: go-cid ]$ # worked!
```

**Comment by hermanjunge** [comment]
Also, I tried with `ln -s /Users/hj/dev/go/src/github.com/ipfs/go-cid /tmp/1/2/3/4/5/6/7/go-cid` and breaks.
