### ISSUE TITLE
gx hangs.

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/gx#5]
no idea what happened, now running `gx init` anywhere hangs.

```
jbenet @ lorien : ~/go/src/github.com/jbenet/go-multihash * master % gx init
^\SIGQUIT: quit
PC=0x484ab

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x1103, 0xc208012000, 0x110300000000, 0x11000000110000, 0x3e276, 0xc208012000, 0xc208012000, 0x45618, 0x3bba0, 0xdcadd0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/sys_darwin_amd64.s:412 +0xb
semasleep()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/os_darwin.c:438 +0x16c
runtime.onM(0xdcadd0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:257 +0x68
runtime.mstart()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:818

goroutine 5 [syscall]:
runtime.notetsleepg(0xdd5840, 0xffffffffffffffff, 0x1)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/lock_sema.go:266 +0x8c fp=0xc20801d768 sp=0xc20801d728
runtime.signal_recv(0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/sigqueue.go:109 +0x135 fp=0xc20801d7a0 sp=0xc20801d768
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f fp=0xc20801d7e0 sp=0xc20801d7a0
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 1 [select]:
github.com/ipfs/go-ipfs/commands/http.(*client).Send(0xc20802b5b0, 0xf87be8, 0xc2080d4000, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/commands/http/client.go:105 +0xfe9
github.com/whyrusleeping/ipfs-shell.(*Shell).ID(0xc20802b5d0, 0x0, 0x0, 0x0, 0x805440, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/whyrusleeping/ipfs-shell/shell.go:55 +0x2d0
main.(*PM).CheckDaemon(0xc20800b600, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/whyrusleeping/gx/main.go:41 +0x59
main.main()
	/Users/jbenet/go/src/github.com/whyrusleeping/gx/main.go:56 +0x2ae

goroutine 7 [chan receive]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics.func·004()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics/metrics.go:321 +0x80
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics.init·1
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics/metrics.go:328 +0x76

goroutine 8 [select]:
net/http.(*persistConn).roundTrip(0xc2080cf600, 0xc20802b8b0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208032090, 0xc2080d0f70, 0xc20803ba00, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:235 +0x558
net/http.send(0xc2080d0f70, 0xf86948, 0xc208032090, 0x3d, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xdca360, 0xc2080d0f70, 0x3d, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xdca360, 0xc2080d0f70, 0xad7928, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xdca360, 0xc2080d0f70, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:177 +0x192
github.com/ipfs/go-ipfs/commands/http.func·001()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/commands/http/client.go:90 +0x59
created by github.com/ipfs/go-ipfs/commands/http.(*client).Send
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/commands/http/client.go:102 +0xc15

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc2080b48b0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080b48b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080b4850, 0xc2080bc000, 0x1000, 0x1000, 0x0, 0xf86160, 0xc20802ba28)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c098, 0xc2080bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0xf88df0, 0xc20802c098, 0xc2080cf658, 0xc2080bc000, 0x1000, 0x1000, 0xf74010, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20800b840, 0xc2080bc000, 0x1000, 0x1000, 0xc207ffd3f5, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080549c0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2080549c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080cf600)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc2080cf600)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc

rax     0xe
rbx     0x7fff5fbfee70
rcx     0x7fff5fbfee28
rdx     0xc20801d6e8
rdi     0x1103
rsi     0x3
rbp     0x45570
rsp     0x7fff5fbfee28
r8      0x1003
r9      0x0
r10     0x30
r11     0x286
r12     0x169e7364d94dc
r13     0x16bced5508a78
r14     0x13eb9395d6282400
r15     0x10
rip     0x484ab
rflags  0x286
cs      0x7
fs      0x0
gs      0x0
```

**Comment by jbenet** [comment]
rebooted ipfs daemon to fix it

**Comment by whyrusleeping** [comment]
bizarre, it looks like the `id` command hung somehow...

**Comment by whyrusleeping** [comment]
closing, this was an issue with the go-ipfs api
