### ISSUE TITLE
Index out of range with `gx view gxDependencies.name`

### ISSUE THREAD

**Issue by chriscool** [whyrusleeping/gx#68]
When running the command in go-ipfs I get:

```
> gx view gxDependencies.name
panic: runtime error: index out of range

goroutine 1 [running]:
main.glob.func8(0xc8200a43c0)
        /home/utilisateur/gocode/src/github.com/whyrusleeping/gx/main.go:633 +0xc52
github.com/codegangsta/cli.Command.Run(0x86e400, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8c81e0, 0x18, 0x0, ...)
        /home/utilisateur/gocode/src/github.com/codegangsta/cli/command.go:179 +0x1397
github.com/codegangsta/cli.(*App).Run(0xc8200906e0, 0xc82000a360, 0x3, 0x3, 0x0, 0x0)
        /home/utilisateur/gocode/src/github.com/codegangsta/cli/app.go:196 +0x1386
github.com/codegangsta/cli.(*App).RunAndExitOnError(0xc8200906e0)
        /home/utilisateur/gocode/src/github.com/codegangsta/cli/app.go:207 +0x54
main.main()
        /home/utilisateur/gocode/src/github.com/whyrusleeping/gx/main.go:90 +0x642

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by whyrusleeping** [comment]
I've fixed this now. Along with a few improvements to how `view` works, for example, you can now do:
```sh
gx view 'gxDependencies[0].name'
```

And also, the slightly more interesting:
```sh
gx view 'gxDependencies[.name=go-libp2p].hash'
```
